authors = ["<oss@fastly.com>"]
description = "An empty application template for the Fastly Compute@Edge environment which simply returns a 200 OK response."
language = "javascript"
manifest_version = 2
name = "Empty starter for JavaScript"
